backlogr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from backlogs.views import BacklogListView, BacklogDetailView, AjaxBacklogRankUpdateView
from backlog_items.views import BacklogItemCreateView, BacklogItemUpdateView
from backlog_items.views import BacklogItemBreakDownView
from react.views import ReactPollView
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #######Auth Views
    #url(r'^accounts/login/$', auth_views.login),
    url('^', include('django.contrib.auth.urls')),

    #######Content Views
    #Start Page
    url(r'^$',
        TemplateView.as_view(template_name="start_page/index.html"),
        name="start_page"),

    #Start Page
    url(r'^product-management-web-development-services/$',
        TemplateView.as_view(template_name="services/services.html"),
        name="services"),

    #######Meta Views
    #Imprint
    url(r'^imprint/$',
        TemplateView.as_view(template_name="meta/imprint.html"),
        name="imprint"),

    #Legal
    url(r'^legal/$',
        TemplateView.as_view(template_name="meta/legal.html"),
        name="legal"),

    #######Backlog Views
    #List View
    url(r'^backlogs/$',
        BacklogListView.as_view(),
        name="backlog_list_view"),
    #Detail View
    url(r'^backlogs/(?P<uuid>[^/]+)/$',
      BacklogDetailView.as_view(),
      name="backlog_detail_view"),
    #Ajax UI Rank Update View
    url(r'^backlogs/rank_update',
      AjaxBacklogRankUpdateView.as_view(),
      name="backlog_rank_update_view"),

    ######Backlog Item Views
    #Create View
    url(r'^backlog_items/create/(?P<backlog_uuid>[^/]+)/$',
      BacklogItemCreateView.as_view(),
      name="backlog_item_create_view"),
    #Breakdown Create View
    url(r'^backlog_items/breakdown/(?P<backlog_uuid>[^/]+)/(?P<parent_uuid>[^/]+)/$',
      BacklogItemBreakDownView.as_view(),
      name="backlog_item_breakdown_view"),
    #Update View
    url(r'^backlog_items/update/(?P<backlog_item_uuid>[^/]+)/$',
        BacklogItemUpdateView.as_view(),
        name="backlog_item_update_view"),

    ######React Views
    url(r'^api/comments/$',
        ReactPollView.as_view(),
        name="comments"),

    url(r'^react/$',
        TemplateView.as_view(template_name="react/tut.html"),
        name="react-tut"),




]

"""
^login/$ [name='login']
^logout/$ [name='logout']
^password_change/$ [name='password_change']
^password_change/done/$ [name='password_change_done']
^password_reset/$ [name='password_reset']
^password_reset/done/$ [name='password_reset_done']
^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='password_reset_confirm']
^reset/done/$ [name='password_reset_complete']
"""

backlog_items/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from backlogs.models import Backlog
import uuid
# Create your models here.
class BacklogItem(models.Model):
    """
    A BacklogItem is either an epic, a user story or a non functional requirement.
    Every item has a integer id, a uuid for the visible part of the application and a short_id.
    The short_id is made out of the backlog name and the integer id, e.g. MYBACKLOG-12.

    Every Backlog Item refers to a user and a backog as foreign key.

    Every Backlog Item has the fields Who, What, Why to specify the user story.
    Every Backlog Item has the field accptance_criteria to specify those in markdown format
    Every item has a field to notes kept in markdown foemat

    Story Points and Business Value define the importance of an item.
    Based on these figures a rank is calculated.

    DateTimeFields track creation and update dates.

    Future Requirements: Items can be broken down in smaller items. and this history should be tracked.

    Todos:
    * Lets calculate the short id based on the short backlog name. Create the short backlog name identifier within the backlog
    """


    BACKLOG_ITEM_CHOICES = (
        ('user_story', 'user_story'),
        ('epic', 'epic'),
        ('non_functional_requirement', 'non_functional_requirement'),
    )
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)

    item_short_id = models.CharField(max_length=200, editable=False, default=0, unique=True)
    sequence_increment = models.PositiveIntegerField(default=0)

    user = models.ForeignKey(User, db_index=True)
    backlog = models.ForeignKey(Backlog, db_index=True)

    backlog_item_type = models.CharField(max_length=50, choices=BACKLOG_ITEM_CHOICES, default= BACKLOG_ITEM_CHOICES[0][0], db_index=True)

    who = models.CharField(max_length=255, blank=True)
    what = models.CharField(max_length=255, blank=True)
    why = models.CharField(max_length=255, blank=True)

    acceptance_criteria = models.TextField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    story_points = models.IntegerField(null=True, blank=True)
    business_value = models.IntegerField(null=True, blank=True)

    #rank default should be the first
    """
    As a pm I want to rerank my cards in the backlog list view
    Every item should be added to the bottom of the list!

    On rearranging the ranks of all instances have to be updated and saved to the database -> DONE
    Within a backlog list the rank must be unique
    """
    list_ui_rank = models.PositiveIntegerField(default=0)

    """
    Used for breakdown of backlog items
    """
    parent_uuid = models.CharField(max_length=255, blank=True)
    is_archive = models.BooleanField(default=True)

    #prio

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = u"Backlog Item"
        verbose_name_plural = u"Backlog Items"

    def __str__(self):
        return str(self.id) + "-" + self.backlog_item_type

    def get_user_story(self):
        return "As a " + self.who + " I'd like to " + self.what + ", so that " + self.why + "."

    def make_item_short_id(self):
        """
        Create a short id based on the backlog short id and the sequence_increment.
        """
        return self.backlog.short_id + "-" + str(self.sequence_increment)

    def save(self, *args, **kwargs):
        if not self.pk:
            #Get the highest UI Rank and assign the new item to the board
            #If no objects exist assign 0
            bi = BacklogItem.objects.filter(backlog=self.backlog)
            if len(bi) != 0:
                try:
                    highest_bi = BacklogItem.objects.select_for_update(nowait=True).order_by('-sequence_increment')[0]
                    self.sequence_increment = highest_bi.sequence_increment + 1
                except KeyError:
                    self.sequence_increment = 0
            else:
                self.sequence_increment = 0

            self.list_ui_rank = len(bi)
            self.item_short_id = self.make_item_short_id()


        super(BacklogItem, self).save(*args, **kwargs)

backlog_items/forms.py
from models import BacklogItem
from django import forms


class BacklogItemForm(forms.ModelForm):
    class Meta:
        model = BacklogItem
        fields = ['user', 'backlog', 'backlog_item_type', 'who', 'what', 'why', 'acceptance_criteria', 'notes', 'story_points', 'business_value']

backlog_items/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponse, Http404
from backlogs.models import Backlog
from models import BacklogItem
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from backlog_items.models import BacklogItem
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from uuid import UUID
import logging
from django.contrib.messages.views import SuccessMessageMixin

logger = logging.getLogger('backlogr')

# Create your views here.
"""
## Backlog Item Requirements

* As a pm I'd like to create a backog item via a form on a single page. -->DONE

* As a pm I'd like to create a backlog item via a form in a modal.

* As a pm I'd like to breakdown a backlog item into smaller backlog items and keeping its parent relation

* As a pm I'd like to update a backlog item via a form on a single page. --> DONE

* As a pm I'd like to update an item via a form in a modal.

## Non functional requirements
* User sees all form fields except User and backlog field -> DONE
* For the single create view the user gets redirected to the referring backlog -> DONE
* For the modal view from the backlog view, the whole creation story should work via ajax.
** The user creates the item, the model closes, the backlog list gets updated.
** In an advanced step anagular or similar should do the job

* Certain events have to be logged such as exceptions as they could be security relevant. -> DONE
"""
class BacklogItemUpdateAjaxView(LoginRequiredMixin, UpdateView):
    pass


class BacklogItemBreakDownView(LoginRequiredMixin, CreateView):
    """
    As a pm I'd like to breakdown a backlog item into smaller backlog items and keeping its parent relation
    """
    model = BacklogItem
    template_name = 'backlog_items/backlog_item_breakdown_view.html'
    fields = ['backlog_item_type', 'who', 'what', 'why', 'acceptance_criteria', 'notes', 'story_points', 'business_value']
    success_message = "Your backlog item was broken down successfully"

    def dispatch(self, *args, **kwargs):
        try:
            val = UUID(kwargs['backlog_uuid'], version=4)
        except ValueError:
            # If it's a value error, then the string
            # is not a valid hex code for a UUID.
            logger.error("An error occurred while breaking down backlog item: %s" % e)
            raise Http404

        self.backlog = get_object_or_404(Backlog, uuid=kwargs['backlog_uuid'])
        logger.debug("BRoke DOwn")
        self.parent_uuid = kwargs['parent_uuid']
        return super(BacklogItemBreakDownView, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('backlog_detail_view', kwargs={'uuid': self.backlog.uuid})

    def form_valid(self, form):

        #user = self.request.user
        backlog_item = form.save(commit=False)
        backlog_item.backlog = self.backlog
        backlog_item.user = self.request.user
        backlog_item.parent_uuid = self.parent_uuid

        return super(BacklogItemBreakDownView, self).form_valid(form)


class BacklogItemUpdateView(LoginRequiredMixin, UpdateView):
    """
    As a pm I'd like to update a backlog item via a form on a single page
    """
    model = BacklogItem
    template_name = 'backlog_items/backlog_item_update_view.html'
    fields = ['backlog_item_type', 'who', 'what', 'why', 'acceptance_criteria', 'notes', 'story_points', 'business_value', 'is_archive']

    def get_object(self, queryset=None):
        try:
            val = UUID(self.kwargs['backlog_item_uuid'], version=4)
        except ValueError as e:
            # If it's a value error, then the string
            # is not a valid hex code for a UUID.
            logger.error("An error occurred while updating a backlog item: %s" % e)
            raise Http404
        obj = get_object_or_404(BacklogItem, uuid=self.kwargs['backlog_item_uuid'])
        self.obj_for_redirect = obj
        return obj

    def get_success_url(self):
        return reverse('backlog_detail_view', kwargs={'uuid': self.obj_for_redirect.backlog.uuid})

class BacklogItemAjaxCreateView(LoginRequiredMixin, CreateView):
    model = BacklogItem
    fields = ['backlog_item_type', 'who', 'what', 'why', 'acceptance_criteria', 'notes', 'story_points', 'business_value']
    pass

class BacklogItemCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    As a pm I'd like to create a backog item via a form on a single page.
    """
    model = BacklogItem
    fields = ['backlog_item_type', 'who', 'what', 'why', 'acceptance_criteria', 'notes', 'story_points', 'business_value']
    template_name = "backlog_items/backlog_item_create_view.html"
    success_message = "Your backlog item was created successfully"
    def dispatch(self, *args, **kwargs):
        try:
            val = UUID(kwargs['backlog_uuid'], version=4)
        except ValueError:
            # If it's a value error, then the string
            # is not a valid hex code for a UUID.
            logger.error("An error occurred while creating backlog item: %s" % e)
            raise Http404

        self.backlog = get_object_or_404(Backlog, uuid=kwargs['backlog_uuid'])
        return super(BacklogItemCreateView, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('backlog_detail_view', kwargs={'uuid': self.backlog.uuid})

    def form_valid(self, form):

        #user = self.request.user
        backlog_item = form.save(commit=False)
        backlog_item.backlog = self.backlog
        backlog_item.user=self.request.user

        return super(BacklogItemCreateView, self).form_valid(form)

templates/backlog_items/backlog_item_breakdown_view.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}
<title>FRNKN - Backlog</title>
{% endblock title %}

{% block js_libraries %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<!--Markdown JS-->
<script src="{% static "js/markdown.js" %}"></script>
{% endblock js_libraries %}

{% block content %}

<div class="container-fluid ta-backlog-projects">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="display-1">Backlog Break Down View</h1>
    </div>
    <div class="col-xs-12 col-md-4 col-lg-6 sidebar">
      <h2>That's a preview of your backlog item:</h2>
      <div class="card card__preview">
        <div class="card-header">
         <small class="muted">Backlog Item: <span id="span-type">User Story</span></small>
        </div>
        <div class="card-block">
          <p class="card-text lead">As a <span id="span-who">WHO</span> I <span id="span-what">WHAT</span>, so that <span id="span-why">WHY</span></p>
        </div>
        <div class="card-block">
          <p class="card-text">Acceptance Criteria:</p>
          <div id="criteria"></div>
          <p class="card-text lead">Story Points: <span id="span-story-points"></span></p>
          <p class="card-text lead">Business Value: <span id="span-business-value"></span></p>
          <hr>
          <p class="card-text">Notes:</p>
          <div id="notes"></div>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-8 col-lg-6">
      <h2>Use this form to write your backlog item:</h2>
      <div class="card card-block">
        <form action="" method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" value="Submit" class="btn btn-success">
      </form>
      </div>
    </div>




  </div>
</div>
</div>



{% block custom_js %}

<script>
  $( document ).ready( function() {

    console.log("loaded");

    //get form field input#who
    $('#id_backlog_item_type').on('change',function (){
      console.log(this.value);
      $('span#span-type').text(this.value);
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#who
    $('input#id_who').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      $('span#span-who').text($(this).val());
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#what
    $('input#id_what').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      $('span#span-what').text($(this).val());
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#why
    $('input#id_why').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      $('span#span-why').text($(this).val());
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#why
    $('textarea#id_acceptance_criteria').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      //$('#criteria').text($(this).val());
      console.log(markdown.toHTML($(this).val()));
      var md = markdown.toHTML($(this).val());
      //$('div#criteria').innerHTML = "Hello World";
      $('div#criteria').html(md);

      //$('div#criteria').text(markdown.toHTML($(this).val()));

      //markdown.toHTML(input.value);
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#id_story_points
    $('input#id_story_points').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      $('span#span-story-points').text($(this).val());
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#id_story_points
    $('input#id_business_value').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      $('span#span-business-value').text($(this).val());
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#why
    $('textarea#id_notes').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      //$('#criteria').text($(this).val());
      console.log(markdown.toHTML($(this).val()));
      var md = markdown.toHTML($(this).val());
      //$('div#criteria').innerHTML = "Hello World";
      $('div#notes').html(md);
    });

  });
</script>
{% endblock custom_js %}
{% endblock %}

templates/backlog_items/backlog_item_create_view.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}
<title>FRNKN - Backlog</title>
{% endblock title %}

{% block js_libraries %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<!--Markdown JS-->
<script src="{% static "js/markdown.js" %}"></script>
{% endblock js_libraries %}

{% block content %}

<div class="container-fluid ta-backlog-projects">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="display-1">Backlog Create View</h1>
    </div>
    <div class="col-xs-12 col-md-4 col-lg-6 sidebar">
      <h2>That's a preview of your backlog item:</h2>
      <div class="card card__preview">
        <div class="card-header">
         <small class="muted">Backlog Item: <span id="span-type">User Story</span></small>
        </div>
        <div class="card-block">
          <p class="card-text lead">As a <span id="span-who">WHO</span> I <span id="span-what">WHAT</span>, so that <span id="span-why">WHY</span></p>
        </div>
        <div class="card-block">
          <p class="card-text">Acceptance Criteria:</p>
          <div id="criteria"></div>
          <p class="card-text lead">Story Points: <span id="span-story-points"></span></p>
          <p class="card-text lead">Business Value: <span id="span-business-value"></span></p>
          <hr>
          <p class="card-text">Notes:</p>
          <div id="notes"></div>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-8 col-lg-6">
      <h2>Use this form to write your backlog item:</h2>
      <div class="card card-block">
        <form action="" method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" value="Submit" class="btn btn-success">
      </form>
      </div>
    </div>




  </div>
</div>
</div>



{% block custom_js %}

<script>
  $( document ).ready( function() {

    console.log("loaded");

    //get form field input#who
    $('#id_backlog_item_type').on('change',function (){
      console.log(this.value);
      $('span#span-type').text(this.value);
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#who
    $('input#id_who').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      $('span#span-who').text($(this).val());
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#what
    $('input#id_what').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      $('span#span-what').text($(this).val());
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#why
    $('input#id_why').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      $('span#span-why').text($(this).val());
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#why
    $('textarea#id_acceptance_criteria').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      //$('#criteria').text($(this).val());
      console.log(markdown.toHTML($(this).val()));
      var md = markdown.toHTML($(this).val());
      //$('div#criteria').innerHTML = "Hello World";
      $('div#criteria').html(md);

      //$('div#criteria').text(markdown.toHTML($(this).val()));

      //markdown.toHTML(input.value);
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#id_story_points
    $('input#id_story_points').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      $('span#span-story-points').text($(this).val());
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#id_story_points
    $('input#id_business_value').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      $('span#span-business-value').text($(this).val());
       /// do your thing here.
       //  use $(this).val() instead e.target.value
    });

    //get form field input#why
    $('textarea#id_notes').on('change keydown keyup',function (){
      console.log("PRESSED", $(this).val());
      //$('#criteria').text($(this).val());
      console.log(markdown.toHTML($(this).val()));
      var md = markdown.toHTML($(this).val());
      //$('div#criteria').innerHTML = "Hello World";
      $('div#notes').html(md);
    });

  });
</script>
{% endblock custom_js %}
{% endblock %}

templates/backlog_items/backlog_item_update_view.html
{% extends "base.html" %}
{% block title %}
<title>FRNKN - Backlog</title>
{% endblock title %}

{% block content %}
<div class="container-fluid ta-backlog-projects">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="display-1">Backlog Update View</h1>
    </div>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Save" />
  </form>
  </div>
  <div class="row">
{% endblock %}